name: Deploy static site to Pages (debug)

on:
  push:
    branches: ["main"]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: true

env:
  SITE_DIR: .   # <- using repo root

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Show repo layout
        run: |
          pwd; ls -la
          echo "---- First 3 levels ----"
          find . -maxdepth 3 -type f | sed 's|^\./||' | head -n 200
      - name: Validate site directory exists and is not empty
        run: |
          if [ ! -d "$SITE_DIR" ]; then
            echo "::error ::Directory '$SITE_DIR' does not exist at repo root."; exit 1; fi
          if [ ! -f "$SITE_DIR/index.html" ]; then
            echo "::warning ::No index.html at $SITE_DIR/ (listing follows)"; find "$SITE_DIR" -maxdepth 2 -type f || true; fi
          COUNT=$(find "$SITE_DIR" -type f | wc -l)
          echo "Found $COUNT files in $SITE_DIR"; [ "$COUNT" -gt 0 ] || (echo "::error ::Folder is empty." && exit 1)
      - name: Add .nojekyll
        run: touch "$SITE_DIR/.nojekyll"
      - uses: actions/upload-pages-artifact@v3
        with:
          path: ./${{ env.SITE_DIR }}

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - id: deployment
        uses: actions/deploy-pages@v4
